# Generated by Django 4.2.6 on 2023-10-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname_test', models.CharField(max_length=100)),
                ('lasttname_test', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
