# Generated by Django 4.2.6 on 2023-10-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='lasttname_test',
            new_name='lastname_test',
        ),
    ]
