# Generated by Django 4.2.6 on 2023-10-31 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_lasttname_test_users_lastname_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
