# Generated by Django 4.2.6 on 2023-11-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_testmodel_delete_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_img', models.ImageField(upload_to='static/img3')),
            ],
        ),
    ]
