# Generated by Django 4.2.6 on 2023-11-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='model_img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
