# Generated by Django 4.2.6 on 2023-11-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_images_model_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='lasttname_test',
            new_name='lastname_test',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='model_img',
            field=models.ImageField(default='', upload_to='img/'),
            preserve_default=False,
        ),
    ]
